#!/bin/sh
#
#This script runs site_data for each of the
#res_data datatypes for Glen Canyon. 
#

#set number of days
DD=40

#location on ftp site for transfer to web
FTP=/wrg/exec/pub/res_levels/ph_format

cat sites | \
 while read site datatype name 
   do
     site_data $site $datatype $DD | grep -vi hdb |grep -v ORACLE > $FTP/${name}.dat
   done




