PROMPT Building demonstration tables.  Please wait.
drop user scott cascade;
CREATE USER scott IDENTIFIED BY "tigeR!2345";
GRANT CONNECT,RESOURCE,DBA  TO scott ;
GRANT UNLIMITED TABLESPACE TO scott;
--ALTER USER SCOTT DEFAULT ROLE CONNECT;

CONNECT scott/tigeR!2345;


CREATE TABLE DEPT (
 DEPTNO NUMBER(2),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13),
 CONSTRAINT DEPT_PK PRIMARY KEY (DEPTNO))
 ROWDEPENDENCIES
 ;

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

CREATE TABLE EMP (
 EMPNO NUMBER(4) NOT NULL,
 ENAME VARCHAR2(10),
 JOB VARCHAR2(9),
 MGR NUMBER(4),
 HIREDATE DATE,
 SAL NUMBER(7, 2),
 COMM NUMBER(7, 2),
 DEPTNO NUMBER(2), 
 CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPNO),
 CONSTRAINT WORKS_IN_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT ON DELETE SET NULL)
 ROWDEPENDENCIES 
 ;

INSERT INTO EMP VALUES
        (7369, 'SMITH',  'CLERK',     7902,
        TO_DATE('17-DEC-1980', 'DD-MON-YYYY'),  800, NULL, 20);
INSERT INTO EMP VALUES
        (7499, 'ALLEN',  'SALESMAN',  7698,
        TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600,  300, 30);
INSERT INTO EMP VALUES
        (7521, 'WARD',   'SALESMAN',  7698,
        TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250,  500, 30);
INSERT INTO EMP VALUES
        (7566, 'JONES',  'MANAGER',   7839,
        TO_DATE('2-APR-1981', 'DD-MON-YYYY'),  2975, NULL, 20);
INSERT INTO EMP VALUES
        (7654, 'MARTIN', 'SALESMAN',  7698,
        TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP VALUES
        (7698, 'BLAKE',  'MANAGER',   7839,
        TO_DATE('1-MAY-1981', 'DD-MON-YYYY'),  2850, NULL, 30);
INSERT INTO EMP VALUES
        (7782, 'CLARK',  'MANAGER',   7839,
        TO_DATE('9-JUN-1981', 'DD-MON-YYYY'),  2450, NULL, 10);
INSERT INTO EMP VALUES
        (7788, 'SCOTT',  'ANALYST',   7566,
        TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES
        (7839, 'KING',   'PRESIDENT', NULL,
        TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
INSERT INTO EMP VALUES
        (7844, 'TURNER', 'SALESMAN',  7698,
        TO_DATE('8-SEP-1981', 'DD-MON-YYYY'),  1500,    0, 30);



COMMIT;

REM ALTER TABLE EMP ADD (
REM        CONSTRAINT MANAGED_BY FOREIGN KEY (MGR) 
REM                  REFERENCES EMP);

CREATE INDEX DEPTNO_ON_EMP ON EMP(DEPTNO);

 
create or replace trigger emp_table_befins
before insert on emp for each row
begin
IF DBMS_SESSION.IS_ROLE_ENABLED('CONNECT')
   THEN
      DBMS_OUTPUT.PUT_LINE('IS_ROLE_ENABLED(CONNECT) is WORKING within TRIGGER call with Oraclehome-' ||dbms_db_version.version || '.' || dbms_db_version.release);
   else
      DBMS_OUTPUT.PUT_LINE('IS_ROLE_ENABLED(CONNECT) is BROKEN within TRIGGER call with Oraclehome-' ||dbms_db_version.version || '.' || dbms_db_version.release);
   END IF;
end;
/

PROMPT Demonstration table build is complete.


PURGE RECYCLEBIN
/



SET SERVEROUTPUT ON
INSERT INTO SCOTT.EMP VALUES (7934, 'MILLgfER', 'CLERK',     7782,   TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10);
--INSERT INTO SCOTT.EMP VALUES (7902, 'FORD',   'ANALYST',   7566,    TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),  3000, NULL, 20);       
--INSERT INTO EMP VALUES  (7876, 'ADAMS',  'CLERK',     7788,  TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20);
--INSERT INTO EMP VALUES  (7900, 'JAMES',  'CLERK',     7698,  TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),   950, NULL, 30);

commit;

--test        
declare 
begin  
  IF (DBMS_SESSION.IS_ROLE_ENABLED('CONNECT')) THEN  
      DBMS_OUTPUT.PUT_LINE('IS_ROLE_ENABLED(CONNECT) is WORKING  outside TRIGGER call with Oraclehome-' || dbms_db_version.version || '.' || dbms_db_version.release);
  ELSE  
     DBMS_OUTPUT.PUT_LINE('IS_ROLE_ENABLED(CONNECT) is BROKEN  outside TRIGGER call with Oraclehome-' ||dbms_db_version.version || '.' || dbms_db_version.release); 
  END IF;     
end;
/

--Cleanup
drop user scott cascade;