#ifndef SHEF_LOCATIONS_INCLUDED
#define SHEF_LCOATIONS_INCLUDED

#define SHEF_FORECAST_YEAR_LOC 9
#define SHEF_FORECAST_MONTH_LOC 15
#define SHEF_ISSUE_MONTH_LOC 35
#define SHEF_ISSUE_YEAR_LOC 29
#define SHEF_VALUE_LOC 90
#define SHEF_VALUE_WIDTH 13

#define SHEF_FORECAST_LENGTH_LOC 60
#define SHEF_FORECAST_PROB_LOC 74
#define SHEF_FORECAST_TYPE_LOC 53


#endif /* have we included shefLocation.h */
