#!/bin/csh -f
#
# first line lets shell know that this is a C script
# the -f tells the shell not to source the .cshrc file
# thus none of the aliases in that file will be valid
# the -x causes an echo of commands to standard output
#
# go out on the internet and get the latest snotel data
#
echo ' ' 
echo '     Attempting to log on to orca in Flagstaff'
echo ' '
umask 022
set nonomatch

set FTP_HOST    = ftpflag.wr.usgs.gov
set FTP_USER    = gcq
set FTP_PASSWD  = gcmrcgcd
#set FTP_FILE    = `cat glen.script`

set noglob
unset noglob

unset noclobber

# Unfortunate long echo for shell variable expansion -- "here document" no good.
echo "open $FTP_HOST \
user $FTP_USER $FTP_PASSWD \
hash \
put crsp_05FEB14.dat \
put crsp_05FEB15.dat \
put crsp_05FEB16.dat \
put crsp_05FEB17.dat \
put crsp_05FEB18.dat \
put crsp_05FEB19.dat \
put crsp_05FEB20.dat \
put crsp_05FEB21.dat \
put crsp_05FEB22.dat \
put crsp_05FEB23.dat \
put crsp_05FEB24.dat \
put crsp_05FEB25.dat \
put crsp_05FEB26.dat \
put crsp_05FEB27.dat \
put crsp_05FEB28.dat \
put crsp_05MAR01.dat \
put crsp_05MAR02.dat \
put crsp_05MAR03.dat \
put crsp_05MAR04.dat \
put crsp_05MAR05.dat \
put crsp_05MAR06.dat \
put crsp_05MAR07.dat \

quit" \
| ftp -n -i -v -d
echo ' '
echo '     FTP Processing complete'
echo ' '















