#!/bin/sh
#
# script takes a single argument: the date to transfer
if [ $# -ne 1 ]
then
    echo "$0 called with incorrect number of command line arguments!"
    exit 2
fi

FTP_FILE=glen_$1.dat
#
# create the glen file from the crsp_file
head -33 crsp_$1.dat > $FTP_FILE
stat=$?
if [ $stat -ne 0 ]
then
    echo "$0 failed to make the $FTP_FILE file!"
    exit $stat
fi
#

echo '     Attempting to log on to orca in Flagstaff'

#the username/password and hostname are stored in the file
# referenced by the -f option in the ncftpput line
# Edit the file to change the details of the transfer
ncftpput -f gcqaccount.dat / $FTP_FILE

stat=$?

\rm -f $FTP_FILE

echo '     FTP Processing complete'
exit $stat




