#!/bin/csh -f
#
# first line lets shell know that this is a C script
# the -f tells the shell not to source the .cshrc file
# thus none of the aliases in that file will be valid
# the -x causes an echo of commands to standard output
#
# go out on the internet and get the latest snotel data
#
echo ' ' 
echo '     Attempting to log on to orca in Flagstaff'
echo ' '
umask 022
set nonomatch

set FTP_HOST    = ftpflag.wr.usgs.gov
set FTP_USER    = gcq
set FTP_PASSWD  = gcmrcgcd
set FTP_FILE    = `cat glen.script`

set noglob
unset noglob

unset noclobber

# Unfortunate long echo for shell variable expansion -- "here document" no good.
echo "open $FTP_HOST \
user $FTP_USER $FTP_PASSWD \
hash \
put $FTP_FILE \
quit" \
| ftp -n -i -v -d
echo ' '
echo '     FTP Processing complete'
echo ' '




