

ALTER TABLE CP_ALGO_PROPERTY MODIFY PROP_NAME VARCHAR2(48 BYTE); 
ALTER TABLE CP_ALGO_PROPERTY_ARCHIVE MODIFY PROP_NAME VARCHAR2(48 BYTE); 
ALTER TABLE CP_ALGO_PROPERTY_ARCHIVE  MODIFY (PROP_VALUE NULL);

--update version table
INSERT INTO TSDB_PROPERTY (PROP_NAME, PROP_VALUE) VALUES ('4.1.3', 'CP_ALGO_PROPERTY prop_name increased and its archive fixed');
/

--Commit
commit;

