# riverwareDMI makefile
# $Id$

TARGET:
	@echo "#######################"
	@echo "# Start building .....#"
	@echo "#######################"
	@echo " "
	@echo "************************************"
	make -f Makefile.pow
	@echo " "
	@echo "************************************"
	make -f Makefile.tot
	@echo " "

clean:
	@echo "#######################"
	@echo "# Start cleaning .....#"
	@echo "#######################"
	@echo " "
	@echo "************************************"
	make -f Makefile.pow clean
	@echo " "
	@echo "************************************"
	make -f Makefile.tot clean
	@echo " "

