all: 
	echo "Making site_data" ;\
	make -f Makefile64.site_data ;\
	echo "Making site_datatype" ;\
	make -f Makefile64.site_datatype ;

clean:
	make -f Makefile64.site_data clean;\
	make -f Makefile64.site_datatype clean;
