LOAD DATA
INFILE 'slotdata.2003'
APPEND
INTO TABLE REF_WA_SLOT_DATA
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
 (LNNO,SECTION,OBJECT,OBJECT_TYPE,SLOT,SLOT_TYPE,UNIT_TYPE,UNIT_SCALE,UNITS,UNIT_FMT,UNIT_SPEC,DATA_TYPE,MODEL_ID CONSTANT 17)

