undefine tbl_owner
define tbl_owner = &1
set echo off

spool wa_sequences.out

PROMPT Creating Sequence for 'REF_WA_RELEASETYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_RELEASETYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_RELEASETYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_RELEASETYPE_SEQ for &&tbl_owner..REF_WA_RELEASETYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_RELEASETYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_SUPPLYTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_SUPPLYTYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_SUPPLYTYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_SUPPLYTYPE_SEQ for &&tbl_owner..REF_WA_SUPPLYTYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_SUPPLYTYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ANNOTATION'
DROP SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ANNOTATION_SEQ for &&tbl_owner..REF_WA_ANNOTATION_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ANNOTATION_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ANNOTATION_BORROW'
DROP SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_BORROW_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_BORROW_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ANNOTATION_BORROW_SEQ for &&tbl_owner..REF_WA_ANNOTATION_BORROW_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ANNOTATION_BORROW_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ANNOTATION_LETTER'
DROP SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_LETTER_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_LETTER_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ANNOTATION_LETTER_SEQ for &&tbl_owner..REF_WA_ANNOTATION_LETTER_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ANNOTATION_LETTER_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_WATERTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_WATERTYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_WATERTYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_WATERTYPE_SEQ for &&tbl_owner..REF_WA_WATERTYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_WATERTYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_WATERTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_DESTINATION_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_DESTINATION_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_DESTINATION_SEQ for &&tbl_owner..REF_WA_DESTINATION_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_DESTINATION_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ACCTTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_ACCTTYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ACCTTYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ACCTTYPE_SEQ for &&tbl_owner..REF_WA_ACCTTYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ACCTTYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ANNOTATIONTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_ANNOTATIONTYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ANNOTATIONTYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ANNOTATIONTYPE_SEQ for &&tbl_owner..REF_WA_ANNOTATIONTYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ANNOTATIONTYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_LEASETYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_LEASETYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_LEASETYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_LEASETYPE_SEQ for &&tbl_owner..REF_WA_LEASETYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_LEASETYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_BORROWTYPE'
DROP SEQUENCE &&tbl_owner..REF_WA_BORROWTYPE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_BORROWTYPE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_BORROWTYPE_SEQ for &&tbl_owner..REF_WA_BORROWTYPE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_BORROWTYPE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_WATER_OWNER'
DROP SEQUENCE &&tbl_owner..REF_WA_WATER_OWNER_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_WATER_OWNER_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_WATER_OWNER_SEQ for &&tbl_owner..REF_WA_WATER_OWNER_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_WATER_OWNER_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_ANNOTATION_LEASE'
DROP SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_LEASE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_ANNOTATION_LEASE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_ANNOTATION_LEASE_SEQ for &&tbl_owner..REF_WA_ANNOTATION_LEASE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_ANNOTATION_LEASE_SEQ to WA_ROLE;


PROMPT Creating Sequence for 'REF_WA_SUPPLY_ROLE'
DROP SEQUENCE &&tbl_owner..REF_WA_SUPPLY_ROLE_SEQ;
CREATE SEQUENCE &&tbl_owner..REF_WA_SUPPLY_ROLE_SEQ START WITH 1 NOCACHE;
CREATE PUBLIC SYNONYM REF_WA_SUPPLY_ROLE_SEQ for &&tbl_owner..REF_WA_SUPPLY_ROLE_SEQ;
GRANT SELECT ON &&tbl_owner..REF_WA_SUPPLY_ROLE_SEQ to WA_ROLE;


spool off

