all: 
	echo "Making inputForecast" ;\
	make -f Makefile.inputForecast ;\
	echo "Making nwsForecast" ;\
	make -f Makefile.nwsForecast ;

clean:
	make -f Makefile.inputForecast clean;\
	make -f Makefile.nwsForecast clean;
