#!/bin/sh

# This script runs res_data for 25 or so reservoirs
# the output is put on the web
#
# Also does it for NIIP Diversion, which uses site_data instead
# but it is here because it uses the html files as well.

#set number of days
DD=40

#location on ftp site for transfer to web
FTP=/wrg/exec/pub/res_levels

#While loop, reads two variables from a file of the format
# 939 silver
# 913 blue 
# ... etc ...

#read the file of reservoirs into the loop
cat reservoirs | \
 while read site name 
   do
     res_data $site $DD | grep -vi hdb |grep -v ORACLE > $FTP/${name}_40d.txt
     cat header.html $FTP/${name}_40d.txt footer.html > $FTP/${name}_40d.html
   done

# Now, do the NIIP Diversion

site_data 451 19 $DD | grep -vi hdb |grep -v ORACLE > $FTP/niip_40d.txt
cat header.html $FTP/niip_40d.txt footer.html > $FTP/niip_40d.html

