#!/bin/csh -f  
setenv LD_LIBRARY_PATH /usr/lib:/lib
source /wrg/home/rclayton/.cshrc
res_data 939 40 >! /wrg/home/rclayton/cron_data/data/40day/silver_40d.txt
res_data 913 40 >! /wrg/home/rclayton/cron_data/data/40day/blue_40d.txt       
res_data 914 40 >! /wrg/home/rclayton/cron_data/data/40day/morrow_40d.txt     
res_data 915 40 >! /wrg/home/rclayton/cron_data/data/40day/crystal_40d.txt    
res_data 916 40 >! /wrg/home/rclayton/cron_data/data/40day/fontenelle_40d.txt 
res_data 917 40 >! /wrg/home/rclayton/cron_data/data/40day/gorge_40d.txt      
res_data 920 40 >! /wrg/home/rclayton/cron_data/data/40day/navajo_40d.txt     
res_data 919 40 >! /wrg/home/rclayton/cron_data/data/40day/glen_40d.txt       
res_data 946 40 >! /wrg/home/rclayton/cron_data/data/40day/pineview_40d.txt   
res_data 940 40 >! /wrg/home/rclayton/cron_data/data/40day/east_40d.txt       
res_data 941 40 >! /wrg/home/rclayton/cron_data/data/40day/echo_40d.txt       
res_data 947 40 >! /wrg/home/rclayton/cron_data/data/40day/rockport_40d.txt   
res_data 964 40 >! /wrg/home/rclayton/cron_data/data/40day/jordanelle_40d.txt 
res_data 953 40 >! /wrg/home/rclayton/cron_data/data/40day/deer_40d.txt       
res_data 928 40 >! /wrg/home/rclayton/cron_data/data/40day/starvation_40d.txt 
res_data 962 40 >! /wrg/home/rclayton/cron_data/data/40day/soldier_40d.txt    
res_data 931 40 >! /wrg/home/rclayton/cron_data/data/40day/scofield_40d.txt   
res_data 932 40 >! /wrg/home/rclayton/cron_data/data/40day/joes_40d.txt       
res_data 961 40 >! /wrg/home/rclayton/cron_data/data/40day/rifle_40d.txt      
res_data 945 40 >! /wrg/home/rclayton/cron_data/data/40day/paonia_40d.txt     
res_data 912 40 >! /wrg/home/rclayton/cron_data/data/40day/taylor_40d.txt     
res_data 948 40 >! /wrg/home/rclayton/cron_data/data/40day/ridgway_40d.txt    
res_data 958 40 >! /wrg/home/rclayton/cron_data/data/40day/mcphee_40d.txt     
res_data 934 40 >! /wrg/home/rclayton/cron_data/data/40day/lemon_40d.txt      
res_data 933 40 >! /wrg/home/rclayton/cron_data/data/40day/vallecito_40d.txt
res_data 942 40 >! /wrg/home/rclayton/cron_data/data/40day/lostcreek_40d.txt
res_data 960 40 >! /wrg/home/rclayton/cron_data/data/40day/redfleet_40d.txt  
site_data 451 19 40 >! /wrg/home/rclayton/cron_data/data/40day/niip_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/silver_40d.txt >! /wrg/exec/pub/res_levels/silver_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/blue_40d.txt >! /wrg/exec/pub/res_levels/blue_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/morrow_40d.txt >! /wrg/exec/pub/res_levels/morrow_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/crystal_40d.txt >! /wrg/exec/pub/res_levels/crystal_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/fontenelle_40d.txt >! /wrg/exec/pub/res_levels/fontenelle_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/gorge_40d.txt >! /wrg/exec/pub/res_levels/gorge_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/navajo_40d.txt >! /wrg/exec/pub/res_levels/navajo_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/glen_40d.txt >! /wrg/exec/pub/res_levels/glen_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/pineview_40d.txt >! /wrg/exec/pub/res_levels/pineview_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/east_40d.txt >! /wrg/exec/pub/res_levels/east_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/echo_40d.txt >! /wrg/exec/pub/res_levels/echo_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/rockport_40d.txt >! /wrg/exec/pub/res_levels/rockport_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/jordanelle_40d.txt >! /wrg/exec/pub/res_levels/jordanelle_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/deer_40d.txt >! /wrg/exec/pub/res_levels/deer_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/starvation_40d.txt >! /wrg/exec/pub/res_levels/starvation_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/soldier_40d.txt >! /wrg/exec/pub/res_levels/soldier_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/scofield_40d.txt >! /wrg/exec/pub/res_levels/scofield_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/joes_40d.txt >! /wrg/exec/pub/res_levels/joes_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/rifle_40d.txt >! /wrg/exec/pub/res_levels/rifle_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/paonia_40d.txt >! /wrg/exec/pub/res_levels/paonia_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/taylor_40d.txt >! /wrg/exec/pub/res_levels/taylor_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/ridgway_40d.txt >! /wrg/exec/pub/res_levels/ridgway_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/mcphee_40d.txt >! /wrg/exec/pub/res_levels/mcphee_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/lemon_40d.txt >! /wrg/exec/pub/res_levels/lemon_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/vallecito_40d.txt >! /wrg/exec/pub/res_levels/vallecito_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/lostcreek_40d.txt >! /wrg/exec/pub/res_levels/lostcreek_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/redfleet_40d.txt >! /wrg/exec/pub/res_levels/redfleet_40d.txt
\grep -v ORACLE /wrg/home/rclayton/cron_data/data/40day/niip_40d.txt >! /wrg/exec/pub/res_levels/niip_40d.txt
setenv FORTYDAY_HOME /wrg/home/rclayton/cron_data/data/40day
setenv AOP_HOME /wrg/exec/pub/res_levels
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/silver_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/silver_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/blue_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/blue_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/morrow_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/morrow_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/crystal_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/crystal_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/fontenelle_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/fontenelle_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/gorge_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/gorge_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/navajo_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/navajo_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/glen_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/glen_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/pineview_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/pineview_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/east_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/east_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/echo_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/echo_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/rockport_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/rockport_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/jordanelle_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/jordanelle_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/deer_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/deer_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/starvation_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/starvation_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/soldier_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/soldier_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/scofield_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/scofield_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/joes_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/joes_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/rifle_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/rifle_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/paonia_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/paonia_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/taylor_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/taylor_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/ridgway_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/ridgway_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/mcphee_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/mcphee_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/lemon_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/lemon_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/vallecito_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/vallecito_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/lostcreek_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/lostcreek_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/redfleet_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/redfleet_40d.html
cat $FORTYDAY_HOME/40day_header.txt $AOP_HOME/niip_40d.txt $FORTYDAY_HOME/40day_footer.txt >! $AOP_HOME/niip_40d.html
