#!/bin/csh -f
#
# first line lets shell know that this is a C script
# the -f tells the shell not to source the .cshrc file
# thus none of the aliases in that file will be valid
# the -x causes an echo of commands to standard output
#
# go out on the internet and get the latest snotel data
#
echo ' ' 
echo '     Attempting to log on to NRCS computer in Portland'
echo ' '
umask 022
set nonomatch

set FTP_HOST    = wcc.nrcs.usda.gov
set FTP_DIR     = .
set FTP_USER    = usbr49
set FTP_PASSWD  = kb287u

set noglob
unset noglob

unset noclobber

# Unfortunate long echo for shell variable expansion -- "here document" no good.
echo "open $FTP_HOST \
user $FTP_USER $FTP_PASSWD \
binary \
hash \
cd $FTP_DIR \
get gunnison.out \
get gunnison.shef \
quit" \
| ftp -n -i -v -d
echo ' '
echo '     FTP Processing complete'
echo ' '
