#!/bin/csh -f
#delete the files
\rm gunnison.out
\rm gunnison.shef
touch marker.delete
#activate the get_snotel script which get the data from portland
get_guntemps
#see if new files have come back
set sa = (`ls -at`)
if ($sa[1] != marker.delete)then
    echo ''
    echo '    new files were retrieved from NRCS  -> continue processing'
    echo  
    source /wrg/hdb/HDB_applications/.cshrc_hdb_app
    rehash
    /wrg/hdb/HDB_applications/bin/guntemps2hdb.pl uchdba rocky98 < gunnison.out
else 
    echo 'FTP transfer failed!'
    exit 1
endif
echo ' ' 
echo '     The script - get_load_guntemps - is  complete'
echo ' '
