#!/bin/csh -f
#delete the files
\rm gunnison.txt
touch marker.delete
#activate the get_snotel script which get the data from portland
./get_guntemps
#see if new files have come back
set sa = (`ls -at`)
if ($sa[1] != marker.delete)then
    echo ''
    echo '    new files were retrieved from NRCS  -> continue processing'
    echo  
    source $HDB_ENV/.cshrc_hdb_app
    rehash
    $HDB_ENV/bin/guntemps2hdb.pl gunnison.txt app_user uchdb2
else 
    echo 'FTP transfer failed!'
    exit 1
endif
\rm marker.delete
echo ' ' 
echo '     The script - get_load_guntemps - is  complete'
echo ' '
