#  The version for use with C and Oracle follows:

include ../../Environ

######################### Directives ###############################

main: links

links:
	cd $(HDB_APP_BIN) ; \
	rm -f guntemps2hdb.pl ; \
	ln -s ../gun_temps/src/guntemps2hdb.pl guntemps2hdb.pl ; \
	cd $(HDB_ENV)/gun_temps/src
