PROMPT Creating REF_CODES Table CG_REF_CODES and Indexes
CREATE TABLE CG_REF_CODES
  (RV_DOMAIN VARCHAR2(100) NOT NULL
  ,RV_LOW_VALUE VARCHAR2(240) NOT NULL
  ,RV_HIGH_VALUE VARCHAR2(240)
  ,RV_ABBREVIATION VARCHAR2(240)
  ,RV_MEANING VARCHAR2(240)
  )
tablespace HDB_data
/
CREATE INDEX X_CG_REF_CODES_1 ON CG_REF_CODES
  (RV_DOMAIN
  ,RV_LOW_VALUE)
/
PROMPT Allowable Value Script
PROMPT
PROMPT Finished.
