CREATE ROLE "BOR_AUDIT_ROLE";
CREATE ROLE "CALC_DEFINITION_ROLE";
CREATE ROLE "DERIVATION_ROLE";
CREATE ROLE "HDB_META_ROLE";
CREATE ROLE "META_DATA_ROLE";
CREATE ROLE "MODEL_PRIV_ROLE";
CREATE ROLE "MONTHLY";
CREATE ROLE "REF_META_ROLE";
CREATE ROLE "SAVOIR_FAIRE";
CREATE ROLE "XCMANAGERS";
CREATE ROLE "XCUSERS";
CREATE ROLE "YAO_APP_ROLE";

CREATE ROLE "APP_ROLE";
GRANT "CONNECT" TO "APP_ROLE";
GRANT "MODEL_PRIV_ROLE" TO "APP_ROLE";
GRANT ALTER TABLESPACE TO "APP_ROLE";

CREATE ROLE "DECODES_ROLE";
GRANT "APP_ROLE" TO "DECODES_ROLE";


  CREATE TABLESPACE HDB_USER DATAFILE 
  '/ora/ora_data/yaohdb/users01.dbf' SIZE 104857600
  AUTOEXTEND ON NEXT 1310720 MAXSIZE 32767M
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT 
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
   ALTER DATABASE DATAFILE '/ora/ora_data/yaohdb/users01.dbf' RESIZE 2621440000;

  CREATE TEMPORARY TABLESPACE HDB_TEMP1 TEMPFILE 
  '/ora/ora_data/yaohdb/temp01.dbf' SIZE 33285996544
  AUTOEXTEND ON NEXT 1073741824 MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1073741824;

  CREATE TABLESPACE HDB_IDX DATAFILE 
  '/ora/ora_data/yaohdb/index02.dbf' SIZE 104857600,
  '/ora/ora_data/yaohdb/index01.dbf' SIZE 16777216000
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT 
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
   ALTER DATABASE DATAFILE '/ora/ora_data/yaohdb/index02.dbf' RESIZE 16106127360;
   ALTER DATABASE DATAFILE '/ora/ora_data/yaohdb/index01.dbf' RESIZE 30408704000;

  CREATE TABLESPACE HDB_DATA DATAFILE 
  '/ora/ora_data/yaohdb/data01.dbf' SIZE 10485760000
  LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT 
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;
   ALTER DATABASE DATAFILE '/ora/ora_data/yaohdb/data01.dbf' RESIZE 32212254720;


