CREATE PROFILE "BOR_ADMIN"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER DEFAULT
    CPU_PER_SESSION DEFAULT
    CPU_PER_CALL DEFAULT
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME DEFAULT
    CONNECT_TIME DEFAULT
    PRIVATE_SGA DEFAULT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 365
    PASSWORD_REUSE_TIME 450
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION COMPLEXITY_VERIFICATION_FUNC
    PASSWORD_LOCK_TIME .0102
    PASSWORD_GRACE_TIME 10
;

CREATE PROFILE "BMC_PKK_PROFILE"
LIMIT
    COMPOSITE_LIMIT UNLIMITED
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    IDLE_TIME UNLIMITED
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_TIME UNLIMITED
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME UNLIMITED
;

CREATE PROFILE "BOR_DEFAULT"
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER DEFAULT
    CPU_PER_SESSION DEFAULT
    CPU_PER_CALL DEFAULT
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME DEFAULT
    CONNECT_TIME DEFAULT
    PRIVATE_SGA DEFAULT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_TIME 450
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION COMPLEXITY_VERIFICATION_FUNC
    PASSWORD_LOCK_TIME .0102
    PASSWORD_GRACE_TIME DEFAULT
;

ALTER PROFILE "DEFAULT"
LIMIT
    COMPOSITE_LIMIT UNLIMITED
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    IDLE_TIME UNLIMITED
    CONNECT_TIME UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_TIME UNLIMITED
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION NULL
    PASSWORD_LOCK_TIME 1
    PASSWORD_GRACE_TIME 7
;
