#  The version for use with C and INGRES follows:

include ../../Environ
include make_include

######################### Directives ###############################

TARGET = $(HDB_APP_BIN)/maxflow
OBJS = \
		$(OBJDIR)/maxflow.o

main: $(TARGET)

clean: 
	rm -f  $(TARGET)  $(OBJS)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(LIBS) -o $(TARGET)

$(OBJDIR)/maxflow.o: \
					maxflow.pc 
	proc iname=maxflow.pc include=$(HDB_APP_INCLUDE)
	$(CC) $(CFLAGS) -c maxflow.c -o $@
