# riverwareDMI.Out makefile
# $Id$

include ../../Environ

OBJDIR = $(HDB_ENV)/riverwareDMI/obj
INCLUDES = -I$(HDB_APP_INCLUDE) -I$(TK_INCLUDES)
#May need -lsocket for Solaris compile
LIBS = $(HDB_LIBS) -ldl -lm $(TK_LIBS) -lnsl
CFLAGS = -ansi -Wall -g -DANSIPROTO $(INCLUDES)

TARGET = $(HDB_APP_BIN)/riverwareDMI.Out

OBJS = $(OBJDIR)/riverwareDMI.Out.o\
	$(OBJDIR)/readDataFile.o\
	$(OBJDIR)/DmiSaveModelData.o\
	$(OBJDIR)/DmiSaveRealData.o

LOCAL_INCS = dmiOut.h 

GLOBAL_INCS = $(HDB_APP_INCLUDE)/dmi_utils.h \
              $(HDB_APP_INCLUDE)/dmiGlobals.h

INTERMED_PROC_FILES = \
	DmiSaveRealData.c \
	DmiSaveModelData.c

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) $(LIBS)
	if test ! -h $(HDB_APP_BIN)/riverwareDMI.Out.GUI.tk ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/riverwareDMI.Out.GUI.tk riverwareDMI.Out.GUI.tk ; \
	   cd ../riverwareDMI/src/ ; \
	fi 
	if test ! -h $(HDB_APP_BIN)/RW.24m.OutputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.24m.OutputDMI.sh RW.24m.OutputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi
	if test ! -h $(HDB_APP_BIN)/RW.BHOPS.OutputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.BHOPS.OutputDMI.sh RW.BHOPS.OutputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi
	if test ! -h $(HDB_APP_BIN)/RW.LC.24m.OutputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.LC.24m.OutputDMI.sh RW.LC.24m.OutputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi
	if test ! -h $(HDB_APP_BIN)/RW.UC.24m.OutputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.UC.24m.OutputDMI.sh RW.UC.24m.OutputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi

clean: 
	rm -f $(OBJS) ; \
	rm -f $(TARGET) ; \
	rm -f $(HDB_APP_BIN)/RW.BHOPS.OutputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/RW.24m.OutputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/RW.UC.24m.OutputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/RW.LC.24m.OutputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/riverwareDMI.Out.GUI.tk ; \
	rm -f $(INTERMED_PROC_FILES) ; \
	rm -f *.lis

######################
# TARGET DEFINITIONS #
######################

$(OBJDIR)/DmiSaveModelData.o: \
	DmiSaveModelData.pc \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_INCLUDE)/typedefs.h \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	proc code=ansi_c CHAR_MAP=string sqlcheck=semantics userid=$(DBA)/$(DBA_PASSWD) iname=DmiSaveModelData.pc include=$(HDB_APP_INCLUDE)
	$(CC) $(CFLAGS) -c DmiSaveModelData.c -o $@

$(OBJDIR)/DmiSaveRealData.o: \
	DmiSaveRealData.pc \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_INCLUDE)/typedefs.h \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	proc code=ansi_c CHAR_MAP=string sqlcheck=semantics userid=$(DBA)/$(DBA_PASSWD) iname=DmiSaveRealData.pc include=$(HDB_APP_INCLUDE)
	$(CC) $(CFLAGS) -c DmiSaveRealData.c -o $@

$(OBJDIR)/riverwareDMI.Out.o: \
	riverwareDMI.Out.c \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	$(CC) $(CFLAGS) -c riverwareDMI.Out.c -o $@

$(OBJDIR)/readDataFile.o: \
	readDataFile.c \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	$(CC) $(CFLAGS) -c readDataFile.c -o $@

