# riverwareDMI.In makefile
# $Id$

include ../../Environ

OBJDIR = $(HDB_ENV)/riverwareDMI/obj
INCLUDES = -I$(HDB_APP_INCLUDE) -I$(TK_INCLUDES) -I/usr/local/X11R5/include
#May need -lsocket for Solaris compile
LIBS = $(HDB_LIBS) -ldl -lm $(TK_LIBS) -lnsl
CFLAGS = -ansi -Wall -g -DANSIPROTO $(INCLUDES)

TARGET = $(HDB_APP_BIN)/riverwareDMI.In

OBJS = 	$(OBJDIR)/SqlGetDmiData.o \
	$(OBJDIR)/writeDataFile.o \
	$(OBJDIR)/PrepareForQueries.o \
	$(OBJDIR)/riverwareDMI.In.o

LOCAL_INCS = dailyDmiIn.h

GLOBAL_INCS = $(HDB_APP_INCLUDE)/dmi_utils.h \
              $(HDB_APP_INCLUDE)/dmiGlobals.h

INTERMED_PROC_FILES = \
	SqlGetDmiData.c

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) $(LIBS)
	if test ! -h $(HDB_APP_BIN)/riverwareDMI.In.GUI.tk ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/riverwareDMI.In.GUI.tk riverwareDMI.In.GUI.tk ; \
	   cd ../riverwareDMI/src/ ; \
	fi
	if test ! -h $(HDB_APP_BIN)/RW.24m.InputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.24m.InputDMI.sh RW.24m.InputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi
	if test ! -h $(HDB_APP_BIN)/RW.BHOPS.InputDMI.sh ; then \
	   cd $(HDB_APP_BIN) ; \
	   ln -s ../riverwareDMI/src/RW.BHOPS.InputDMI.sh RW.BHOPS.InputDMI.sh ; \
	   cd ../riverwareDMI/src/ ; \
	fi

clean: 
	rm -f $(OBJS) ; \
	rm -f $(TARGET) ; \
	rm -f $(HDB_APP_BIN)/RW.BHOPS.InputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/RW.24m.InputDMI.sh ; \
	rm -f $(HDB_APP_BIN)/riverwareDMI.In.GUI.tk ;
	rm -f $(INTERMED_PROC_FILES)
	rm -f *.lis

######################
# TARGET DEFINITIONS #
######################

$(OBJDIR)/riverwareDMI.In.o: \
	riverwareDMI.In.c \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	$(CC) $(CFLAGS) -c riverwareDMI.In.c -o $@

$(OBJDIR)/SqlGetDmiData.o: \
	SqlGetDmiData.pc \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a 
	proc code=ansi_c iname=SqlGetDmiData.pc include=$(HDB_APP_INCLUDE)
	$(CC) $(CFLAGS) -c SqlGetDmiData.c -o $@

$(OBJDIR)/writeDataFile.o: \
	writeDataFile.c \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	$(CC) $(CFLAGS) -c writeDataFile.c -o $@

$(OBJDIR)/PrepareForQueries.o: \
	PrepareForQueries.c \
	$(LOCAL_INCS) \
	$(GLOBAL_INCS) \
	$(HDB_APP_LIB)/libutils.a \
	$(HDB_APP_LIB)/libhdb.a \
	$(HDB_APP_LIB)/libdmi.a
	$(CC) $(CFLAGS) -c PrepareForQueries.c -o $@

