# riverwareDMI makefile
# $Id$

TARGET:
	@echo "#######################"
	@echo "# Start building .....#"
	@echo "#######################"
	@echo " "
	@echo "************************************"
	make -f Makefile.input
	@echo " "
	@echo "************************************"
	make -f Makefile.output
	@echo " "

clean:
	@echo "#######################"
	@echo "# Start cleaning .....#"
	@echo "#######################"
	@echo " "
	@echo "************************************"
	make -f Makefile.input clean
	@echo " "
	@echo "************************************"
	make -f Makefile.output clean
	@echo " "

