start ../src/uc_resdata_extract.sql Powell 919
start ../src/uc_resdata_extract.sql Navajo 920
start ../src/uc_resdata_extract.sql Pineview 946 
start ../src/uc_resdata_extract.sql East_Canyon 940 
start ../src/uc_resdata_extract.sql Lost_Creek 942
start ../src/uc_resdata_extract.sql Echo 941 
start ../src/uc_resdata_extract.sql Rockport 947 
start ../src/uc_resdata_extract.sql Red_Fleet 960 
start ../src/uc_resdata_extract.sql Paonia 945 
start ../src/uc_resdata_extract.sql Blue_Mesa 913
start ../src/uc_resdata_extract.sql Morrow_Point 914 
start ../src/uc_resdata_extract.sql Crystal 915 
start ../src/uc_resdata_extract.sql Ridgway 948 
start ../src/uc_resdata_extract.sql Lemon 934 
start ../src/uc_resdata_extract.sql Vallecito 933
start ../src/uc_resdata_extract.sql Jordanelle 964 
start ../src/uc_resdata_extract.sql Starvation 928
start ../src/uc_resdata_extract.sql El_Vado 2685
start ../src/uc_resdata_extract.sql Heron 2686 
start ../src/uc_resdata_extract_hour.sql East_Canyon_Hourly 940
start ../src/uc_resdata_extract_hour.sql Echo_Hourly 941
start ../src/uc_resdata_extract_hour.sql Lost_Creek_Hourly 942
start ../src/uc_resdata_extract_hour.sql Pineview_Hourly 946
start ../src/uc_resdata_extract_hour.sql Rockport_Hourly 947
exit;
