CREATE OR REPLACE TRIGGER HDB_COLLECTION_SYSTEM_PK_TRIG
  BEFORE INSERT OR UPDATE ON HDB_COLLECTION_SYSTEM
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.COLLECTION_SYSTEM_ID := populate_pk.get_pk_val( 'HDB_COLLECTION_SYSTEM', FALSE );  END IF; ELSIF updating THEN :new.COLLECTION_SYSTEM_ID := :old.COLLECTION_SYSTEM_ID; END IF; END;
/
show errors trigger HDB_COLLECTION_SYSTEM_PK_TRIG;