  CREATE OR REPLACE TRIGGER HDB_LOADING_APPLICATIO_PK_TRIG
  BEFORE INSERT OR UPDATE ON HDB_LOADING_APPLICATION
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.LOADING_APPLICATION_ID := populate_pk.get_pk_val( 'HDB_LOADING_APPLICATION', FALSE );  END IF; ELSIF updating THEN :new.LOADING_APPLICATION_ID := :old.LOADING_APPLICATION_ID; END IF; END;
/

show errors trigger HDB_LOADING_APPLICATIO_PK_TRIG;