  CREATE OR REPLACE TRIGGER HDB_SITE_DATATYPE_PK_TRIG
  BEFORE INSERT OR UPDATE ON HDB_SITE_DATATYPE
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.SITE_DATATYPE_ID := populate_pk.get_pk_val( 'HDB_SITE_DATATYPE', FALSE );  END IF; ELSIF updating THEN :new.SITE_DATATYPE_ID := :old.SITE_DATATYPE_ID; END IF; END;
/

show errors trigger HDB_SITE_DATATYPE_PK_TRIG;