  CREATE OR REPLACE TRIGGER HDB_METHOD_CLASS_PK_TRIG
  BEFORE INSERT OR UPDATE ON HDB_METHOD_CLASS
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.METHOD_CLASS_ID := populate_pk.get_pk_val( 'HDB_METHOD_CLASS', FALSE );  END IF; ELSIF updating THEN :new.METHOD_CLASS_ID := :old.METHOD_CLASS_ID; END IF; END;
/

show errors trigger HDB_METHOD_CLASS_PK_TRIG;