  CREATE OR REPLACE TRIGGER REF_EXT_SITE_DATA_MAP_PK_TRIG
  BEFORE INSERT OR UPDATE ON REF_EXT_SITE_DATA_MAP
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.MAPPING_ID := populate_pk.get_pk_val( 'REF_EXT_SITE_DATA_MAP', FALSE );  END IF; ELSIF updating THEN :new.MAPPING_ID := :old.MAPPING_ID; END IF; END;
/

show errors trigger REF_EXT_SITE_DATA_MAP_PK_TRIG;