  CREATE OR REPLACE TRIGGER REF_AGG_DISAGG_PK_TRIG
  BEFORE INSERT OR UPDATE ON REF_AGG_DISAGG
  REFERENCING FOR EACH ROW
  BEGIN IF inserting THEN IF populate_pk.pkval_pre_populated = FALSE THEN :new.AGG_DISAGG_ID := populate_pk.get_pk_val( 'REF_AGG_DISAGG', FALSE );  END IF; ELSIF updating THEN :new.AGG_DISAGG_ID := :old.AGG_DISAGG_ID; END IF; END;
/
show errors trigger REF_AGG_DISAGG_PK_TRIG;