DROP TRIGGER HDB_AGEN_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_ATTR_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_COLLECTION_SYSTEM_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_COMPUTED_DATATYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_DAMTYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_DATATYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_DATA_SOURCE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_DIMENSION_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_GAGETYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_LOADING_APPLICATIO_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_METHOD_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_METHOD_CLASS_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_MODEL_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_OBJECTTYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_RIVER_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_SITE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_SITE_DATATYPE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_STATE_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_UNIT_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DROP TRIGGER HDB_USBR_OFF_PK_TRIG ;
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
