#!/bin/bash
hydromet_report $*
stat=$?
if [ $stat -ne 0 ]
then
    exit $stat
fi

file=hydromet_$3.dat
echo "              Printing Hydromet data"
./prp $file
echo "       Transferring data to Hydromet"
# annoying stuff to deal with letter case 
# because VMS does wierd things to conserve the case both in NFS and scp
# hydromet_##SEP.dat becomes HYDROMET_##$SEP.$DAT on vms
# so we handle it ahead of time.
# In vms a $ in the name indicates a case shift
file_lowercase=`echo $file | tr A-Z a-z`

chmod -f ug+rw,o+r $file
scp -p $file hydromet@zippy:scada_files/$file_lowercase 2>/dev/null


#old stuff
#do we need to do this?
#ssh zippy -l hydromet "set sec [.scada_files]$u /prot=(s:rwed,o:rwed,g:rwed,w:re)"

#
# these commands below are the previous version, and are less efficient.
#
# now, we take advantage of the nfsmount on zimmy, and
# copy the file to the alpha directory as mounted on zimmy
#scp `cat dum` zimmy:/alpdata/archives/xferscada/$u
# now, login to the alpha and copy the file to where it needs to be
# this command complains that $U is not locked, but it is, so...
#ssh -1 slcalp -l hydromet 'pipe set def custom$:[archives.xferscada]'" && unlock $U && copy $U uc280:[hydromet.scada_files]"
#instead, do this command which just changes the protection on the file.
#ssh zippy -l hydromet "set sec [.scada_files]$U /prot=(s:rwed,o:rwed,g:rwed,w:re)"
# then, delete the copied file
#ssh zimmy "rm /alpdata/archives/xferscada/$u"
#done!

