#!/bin/sh
# This script was set up for the Western Colorado Area Office to 
# generate data files on athena that Erik Knight will pick up each
# day to create thumbnail and full size images of graphed data for
# the reservoirs they manage and monitor.  The reservoirs are Blue 
# Mesa (BM), Morrow Point (MP), Crystal (CR), Crawford (CW), 
# Fruitgrowers (FG), Paonia (PA), Ridgway (RW), Rifle Gap (RG),
# Silverjack (SJ), Taylor Park (TP), Vega (VG), Navajo (NV), 
# Vallecito (VC), Lemon (LM), Jackson Gulch (JG), McPhee (MC).
#
# The data files will be located in a directory set up on athena
# in /wrg/exec/pub/wcao_res_levels.

#location on ftp site for transfer to web
FTP=/wrg/exec/pub/wcao_res_levels

#set number of days
DD=40

#While loop, reads two variables from a file of the format
# 939 silver
# 913 blue 
# ... etc ...

#read the file of reservoirs into the loop
cat wcao_reservoirs | \
 while read site name 
   do
     res_data $site $DD > data/${name}_40d_res.txt
     wcao_data $site $DD > data/${name}_40d_wcao.txt
     paste data/${name}_40d_res.txt data/${name}_40d_wcao.txt | grep -vi hdb |grep -v ORACLE > $FTP/${name}_40d.txt
   done

cat wcao_sites | \
 while read site datatype name 
   do
     site_data $site $datatype $DD | grep -vi hdb |grep -v ORACLE > $FTP/${name}_40d.txt
   done

