#!/bin/bash
#
#	/etc/rc.d/init.d/hdbprocs
#
# Starts the HDB processes for routing specs and computation processes
#
# chkconfig: 345 95 5
# description: HDB Processes
# processname: hdbprocs
# Source function library.
test -x /etc/init.d/functions && . /etc/init.d/functions


#============= CHANGE THESE ===============
#
HDB_ENV=/wrg/hdb/HDB2_applications; export HDB_ENV;
HDB_DBA=uchdba

# fix issue with Linux systems where su is limited to wheel group members
if [ `whoami` = $HDB_DBA ]
then
  command="sh -c"
else
  command="su - $HDB_DBA -c"
fi

#
#================================


test -x $HDB_ENV/startup_processes/src/checkapps.pl || exit 0

RETVAL=0
prog="HDB Processes"
script="$HDB_ENV/startup_processes/src/checkapps.pl -a $HOME/.app_user_login"
start() {
	echo -n $"Starting $prog: "
	$command "$script start"
	echo
}

stop() {
	echo -n $"Stopping $prog: "
	$command "$script stop"
	echo
}

status() {
	$command "$script status"
}

#
#	See how we were called.
#
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  reload|restart)
	stop
	start
	;;
   status)
	status
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit
