#!/bin/bash
#
#	/etc/rc.d/init.d/hdbprocs
#
# Starts the HDB processes for routing specs and computation processes
#
# chkconfig: 345 95 5
# description: HDB Processes
# processname: hdbprocs
# Source function library.
test -x /etc/init.d/functions && . /etc/init.d/functions

HDB_ENV=/wrg/hdb/HDB2_applications; export HDB_ENV;

test -x $HDB_ENV/startup_processes/src/checkapps.pl || exit 0

RETVAL=0
prog="HDB Processes"

start() {
    echo -n $"Starting $prog: "
	su - uchdba -c "$HDB_ENV/startup_processes/src/checkapps.pl -a ~uchdba/.app_user_login start"
	echo
}

stop() {
	echo -n $"Stopping $prog: "
	su - uchdba -c "$HDB_ENV/startup_processes/src/checkapps.pl -a ~uchdba/.app_user_login stop"
	echo
}

status() {
	su - uchdba -c "$HDB_ENV/startup_processes/src/checkapps.pl -a ~uchdba/.app_user_login status"
}

#
#	See how we were called.
#
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  reload|restart)
	stop
	start
	;;
   status)
	status
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit
