#  The version for use with C and Oracle follows:

include ../../Environ

######################### Directives ###############################

main: links

links:
	cd $(HDB_APP_BIN) ; \
	rm -f elpaso2hdb.pl ; \
	ln -s ../elpaso/src/elpaso2hdb.pl .; \
	cd ../elpaso/src
