GRANT SELECT ON ALARM_CURRENT TO PUBLIC;
GRANT UPDATE ON ALARM_CURRENT TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_CURRENT TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_CURRENT TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_CURRENT TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_CURRENT TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_CURRENT TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_CURRENT TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_CURRENT TO CALC_DEFINITION_ROLE;

GRANT SELECT ON ALARM_EVENT TO PUBLIC;
GRANT UPDATE ON ALARM_EVENT TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_EVENT TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_EVENT TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_EVENT TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_EVENT TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_EVENT TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_EVENT TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_EVENT TO CALC_DEFINITION_ROLE;

GRANT SELECT ON ALARM_GROUP TO PUBLIC;
GRANT UPDATE ON ALARM_GROUP TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_GROUP TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_GROUP TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_GROUP TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_GROUP TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_GROUP TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_GROUP TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_GROUP TO CALC_DEFINITION_ROLE;

GRANT SELECT ON ALARM_HISTORY TO PUBLIC;
GRANT UPDATE ON ALARM_HISTORY TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_HISTORY TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_HISTORY TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_HISTORY TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_HISTORY TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_HISTORY TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_HISTORY TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_HISTORY TO CALC_DEFINITION_ROLE;

GRANT SELECT ON ALARM_LIMIT_SET TO PUBLIC;
GRANT UPDATE ON ALARM_LIMIT_SET TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_LIMIT_SET TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_LIMIT_SET TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_LIMIT_SET TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_LIMIT_SET TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_LIMIT_SET TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_LIMIT_SET TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_LIMIT_SET TO CALC_DEFINITION_ROLE;

GRANT SELECT ON ALARM_SCREENING TO PUBLIC;
GRANT UPDATE ON ALARM_SCREENING TO SAVOIR_FAIRE;
GRANT SELECT ON ALARM_SCREENING TO SAVOIR_FAIRE;
GRANT INSERT ON ALARM_SCREENING TO SAVOIR_FAIRE;
GRANT DELETE ON ALARM_SCREENING TO SAVOIR_FAIRE;
GRANT UPDATE ON ALARM_SCREENING TO CALC_DEFINITION_ROLE;
GRANT SELECT ON ALARM_SCREENING TO CALC_DEFINITION_ROLE;
GRANT INSERT ON ALARM_SCREENING TO CALC_DEFINITION_ROLE;
GRANT DELETE ON ALARM_SCREENING TO CALC_DEFINITION_ROLE;

GRANT SELECT ON EMAIL_ADDR TO PUBLIC;
GRANT UPDATE ON EMAIL_ADDR TO SAVOIR_FAIRE;
GRANT SELECT ON EMAIL_ADDR TO SAVOIR_FAIRE;
GRANT INSERT ON EMAIL_ADDR TO SAVOIR_FAIRE;
GRANT DELETE ON EMAIL_ADDR TO SAVOIR_FAIRE;
GRANT UPDATE ON EMAIL_ADDR TO CALC_DEFINITION_ROLE;
GRANT SELECT ON EMAIL_ADDR TO CALC_DEFINITION_ROLE;
GRANT INSERT ON EMAIL_ADDR TO CALC_DEFINITION_ROLE;
GRANT DELETE ON EMAIL_ADDR TO CALC_DEFINITION_ROLE;

GRANT SELECT ON FILE_MONITOR TO PUBLIC;
GRANT UPDATE ON FILE_MONITOR TO SAVOIR_FAIRE;
GRANT SELECT ON FILE_MONITOR TO SAVOIR_FAIRE;
GRANT INSERT ON FILE_MONITOR TO SAVOIR_FAIRE;
GRANT DELETE ON FILE_MONITOR TO SAVOIR_FAIRE;
GRANT UPDATE ON FILE_MONITOR TO CALC_DEFINITION_ROLE;
GRANT SELECT ON FILE_MONITOR TO CALC_DEFINITION_ROLE;
GRANT INSERT ON FILE_MONITOR TO CALC_DEFINITION_ROLE;
GRANT DELETE ON FILE_MONITOR TO CALC_DEFINITION_ROLE;

GRANT SELECT ON PROCESS_MONITOR TO PUBLIC;
GRANT UPDATE ON PROCESS_MONITOR TO SAVOIR_FAIRE;
GRANT SELECT ON PROCESS_MONITOR TO SAVOIR_FAIRE;
GRANT INSERT ON PROCESS_MONITOR TO SAVOIR_FAIRE;
GRANT DELETE ON PROCESS_MONITOR TO SAVOIR_FAIRE;
GRANT UPDATE ON PROCESS_MONITOR TO CALC_DEFINITION_ROLE;
GRANT SELECT ON PROCESS_MONITOR TO CALC_DEFINITION_ROLE;
GRANT INSERT ON PROCESS_MONITOR TO CALC_DEFINITION_ROLE;
GRANT DELETE ON PROCESS_MONITOR TO CALC_DEFINITION_ROLE;

--update version table
INSERT INTO TSDB_PROPERTY (PROP_NAME, PROP_VALUE) VALUES ('4.1.1', 'HDB 4.1.1- CALC_DEFINITION_ROLE ,SAVOIR_FAIRE role modified with alarm objects');
/

--Commit
commit;

