

ALTER TABLE CP_COMPUTATION MODIFY CMMNT VARCHAR2(2000 BYTE);
ALTER TABLE CP_COMPUTATION_ARCHIVE MODIFY CMMNT VARCHAR2(2000 BYTE);


--update version table
INSERT INTO TSDB_PROPERTY (PROP_NAME, PROP_VALUE) VALUES ('4.1.4', 'CP_COMPUTATION CMMNT column size increased 2000 along with its archive ');
/

--Commit
commit;

